name: musiclum
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  retrofit: ^4.1.0
  get_it: ^7.6.7
  dio: ^5.4.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  like_button: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/foreground.png"
  adaptive_icon_background: "#f0f5ff"

flutter:
  uses-material-design: true
